### ISSUE TITLE
Writer class not working on lobo micropython

### ISSUE THREAD

**Issue by julien123123** [peterhinch/micropython-font-to-py#10]
I'm trying to port one of my scripts that uses the writer class from the official micropython on an ESP32 to the Lobo micropython. When micropython arrives at the writer class, it always rises this error: 
`Traceback (most recent call last):
  File "<stdin>", line 16, in <module>
  File "writer.py", line 56, in __init__
ValueError: Font must be horizontally mapped.`
The converted fonts worked on very well on micropython with the ssd1306 adafruit driver. Any ideas?

**Comment by peterhinch** [comment]
I have only tested with official builds and the official ssd1306 driver.

That said, a font file is just Python code. If you look at your font file you should find a function **hmap** in the code which simply returns True if the font is horizontally mapped. The line which throws the  exception seems to suggest that your font file has an **hmap** function which is returning False. If your font file's function returns False then the font is indeed not horizontally mapped. If it returns True then I'm baffled. It looks as if there is something very odd about the Loboris port. Try (at the Loboris REPL):

```python
import MyFont
MyFont.hmap()
```
