### ISSUE TITLE
Need help with the mapping

### ISSUE THREAD

**Issue by lehrerhans** [peterhinch/micropython-font-to-py#13]
Hallo Peter,
i made a font with your nice font-to-py tool.
unfortunately the font is displayed not correct on my 1.54 Waveshare Epaper display.
the controller is a ESP32.
i tryed 4 fonts , with the 4 possible combination of hmap and reverse. See Picture.
Unfortunately the font is displayed 90 degree rotated.
I attached the whole source.

I would be happy, if you could help.

regards
christoph (germany)

![font_problem](https://user-images.githubusercontent.com/45143067/48675136-6ee44000-eb55-11e8-88e2-9a350386c387.png)
[font_problem.zip](https://github.com/peterhinch/micropython-font-to-py/files/2592955/font_problem.zip)

**Comment by lehrerhans** [comment]
Hello,

thanks for the answer.
I did some programming to find a solution to rotate the fonts.
I programmed wit pygame a little program which displays the fonts generated from "font_to_py".
And so i found out that the -x Mapping brings the correct solution, but only if i generated a single character. I did these test wit the charackter "A". If i generate and use the whole font it seems so, as if the glyph data differ.

I attached my test-program "Glyph_Drwaing_V4" and two "font-to-py" files.
The Programs shows the character "A" grapfically and prints the Glyph data in the REPL.

font_to_py.py -x -s 65 -l 65 ARIALUNI.TTF 48 arial48x.py
font_to_py.py -x ARIALUNI.TTF 48 arial48x_all.py

arial48x.py with the single "A" in its works fine.
arial48x_all.py with all characters  doesnt work.

So font-to-py seems to deliver the correct data for vertikal mapping , but only for a single generated 
character.

best regards 
Christoph Roters

**Comment by peterhinch** [comment]
Did you try the approach I suggested above? If so, what was the outcome?

**Comment by lehrerhans** [comment]
Hello,
i try to approch like you suggested.
The problem seems to be somewhere in the "font-to-py.py"
The picture shows the result on the E-ink.
![image](https://user-images.githubusercontent.com/45143067/48922052-39688b00-eea4-11e8-90c8-44632f98ff34.png)


if i create a file with only one char with  **font_to_py.py -x -s 65 -l 65 ARIALUNI.TTF 48 arial48x.py**
its working perfect.

if i create the font-to-py file with **font_to_py.py -x -s 65 -l 65 ARIALUNI.TTF 48 arial48x.py**
it shows pixel-garbage.

i attached the code an deleted all testing stuff for better readablity.

**Comment by peterhinch** [comment]
My suggestion was to use the [Writer class](https://github.com/peterhinch/micropython-font-to-py/blob/master/writer/WRITER.md). This is the preferred way to write text to a framebuf.
