### ISSUE TITLE
Incorrect bit-maps generated for 'J', 'K' and 'R' (and perhaps others)

### ISSUE THREAD

**Issue by ironss** [peterhinch/micropython-font-to-py#21]
DejaVu Sans capital J has a negative bitmap left value: the bottom of the J extends underneath the previous character in the string.

DejaVu Sans capital K and R has a bitmap that extends past the 'advance' value. The bottom leg extends underneath the next character in the string.

These problems came about after a previous character spacing fix.

https://github.com/ironss/micropython-font-to-py/commit/e73da4cbbd669148d486b0717c793a5415ce32a2 is a fix that handles both of these.

**Comment by peterhinch** [comment]
Thank you. Now implemented.
