### ISSUE TITLE
Characters in unicode private-use area

### ISSUE THREAD

**Issue by ironss** [peterhinch/micropython-font-to-py#22]
font-to-py does not generate bitmaps for various symbol fonts.

* FontAwesome (https://fontawesome.com/)
* WeatherIcons (https://erikflowers.github.io/weather-icons/)

These font files use the Unicode private-use area for their glyphs.

Font-to-py checks each character in the character set to ensure that it is a printable character, using Python isprintable(); this function considers characters classified as Unicode 'Other' to be non-printable (https://docs.python.org/3/library/stdtypes.html?highlight=isprintable#str.isprintable). 

According to http://www.unicode.org/versions/Unicode9.0.0/ch04.pdf, characters in the private-use areas are classified as 'Other, private use'.

Please can we have an exception for the Unicode private-use areas. Or perhaps drop the is-printable verification for a supplied character set using -c or -k.

Changeset https://github.com/ironss/micropython-font-to-py/commit/e22d99c5c4b2988e294907113dbdf1dddaabbf47 allows characters in the private-use area or the (unicode) BMP, but not in the other private-use areas.

**Comment by peterhinch** [comment]
Thank you. Now implemented.
