### ISSUE TITLE
big font file size

### ISSUE THREAD

**Issue by varna9000** [peterhinch/micropython-font-to-py#36]
Hi Peter,
I've been using this tool for more than year and my biggest concern is the size of the output font file. I'm generating mainly Cyrillic fonts and I've noticed two things - the bigger the font size, the bigger the .py file. Also, if I generate same amount of chars latin letters and same font size, the .py file is smaller. Does the char number in  utf-8 table somehow influence .py file size ( the higher the char number, the bigger the file size)?  I've experimented with small and capital letters. Adding capitals to the font actually generates smaller files size, than the small letters, since the capitals have smaller char number in utf-8 table.

Experiencing the above, eats up a lot of esp8266 memory, even if I compile it to .mpy

**Comment by peterhinch** [comment]
The solution is to use frozen bytecode, which is better than compiling to MPY. Fonts then use Flash space but almost zero RAM.

**Comment by varna9000** [comment]
Thanks, Peter. I'll try this even with the other external modules I'm using in the project.
