### ISSUE TITLE
Can I use this to get all the pixel x, y coordinate positions of a glyph?

### ISSUE THREAD

**Issue by ShaunKulesa** [peterhinch/micropython-font-to-py#37]
Can I use this library to get all the pixel x, y coordinate positions of a glyph? I want to get every pixel in a glyph created in free type. Here's the code I have:

```
import freetype
face = freetype.Face("Arial.ttf")
face.set_char_size( 48*64 )
face.load_char('S')
bitmap = face.glyph
```

**Comment by peterhinch** [comment]
This is really a query about freetype rather than about my code. To answer it I'd have to research freetype to refresh my memory of how it works - it's five years since I used it in earnest to write `font_to_py`. I'm afraid I'm too busy to tackle this at the moment.
