### ISSUE TITLE
tried to create large font file with thousands of character

### ISSUE THREAD

**Issue by tljk** [peterhinch/micropython-font-to-py#41]
![图片](https://user-images.githubusercontent.com/36393586/171649944-6cfe4229-3a1c-422f-93f3-ac4cd7d3ed63.png)
this is what i got from a 3.5k characters file named chinese
the font index seems simply cannot exceed 255, 
`-l or --largest Ordinal value of largest character to be stored. Default 126.`
so, what is the correct way to do so

**Comment by peterhinch** [comment]
I think your deduction is incorrect. The index can accept values up to 65535, and your font exceeds that. The following was issued under CPython 3.8.10:
```python
>>> x = 4
>>> x.to_bytes(2, byteorder="little")
b'\x04\x00'
>>> x = 65535
>>> x.to_bytes(2, byteorder="little")
b'\xff\xff'
>>> x = 65536
>>> x.to_bytes(2, byteorder="little")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: int too big to convert
>>> 
```
