### ISSUE TITLE
Variable character width extended ASCII vs non-extended ASCII

### ISSUE THREAD

**Issue by stroobandt** [peterhinch/micropython-font-to-py#5]
Dear Peter,

I am experiencing considerable variation in character width when creating fonts with 255 versus 128 ASCII characters. See the example below. Is there a way to overcome this?

Also, which ASCII extension code page are you using? This is not documented. Does it depend on my PC settings?
```
$ ./font_to_py.py -x font.ttf 12 font12.py
Writing Python font file.
Height set in 2 passes. Actual height 11 pixels.
Max character width 11 pixels.
font12.py written successfully.

$ ./font_to_py.py -x -l 255 font.ttf 12 font12x.py
Writing Python font file.
Height set in 2 passes. Actual height 12 pixels.
Max character width 9 pixels.
font12x.py written successfully.
```
It does not seem quite logical to me that when more glyphs are present, the slimmer the font gets.

**Comment by stroobandt** [comment]
I have been digging a little deeper…
It seems that only OTF fonts allow their extended ASCII glyphs to be converted successfully.

Conversely, TTF fonts are not showing extended ASCII glyphs properly even though `-l 255` was specified with the command. The `?` character is shown instead.

**Comment by peterhinch** [comment]
Thank you for that information. This may be a limitation of the freetype library. I'll update the code and docs. I guess the best thing is to output a warning (in the hope that freetype is subsequently fixed).
