### ISSUE TITLE
Freely write at different coordinate 

### ISSUE THREAD

**Issue by hunter40415** [peterhinch/micropython-font-to-py#58]
I suggest add this line into the code to avoid having to call out a coordinate every time which make the code look messy
![image](https://github.com/peterhinch/micropython-font-to-py/assets/144647713/512d468e-4e8c-46f8-b0a2-53b5fe088981)
which turn the code from this
![image](https://github.com/peterhinch/micropython-font-to-py/assets/144647713/f10f6712-8e35-4266-9695-1c7e4cad724d)
to this
![image](https://github.com/peterhinch/micropython-font-to-py/assets/144647713/94b980d6-3102-4610-ad9b-be3178e8d155)

**Comment by peterhinch** [comment]
The reason `set_textpos` is a separate method is that, having set the text position, the application might perform many `printstring` calls with the text being added each time at the current cursor point. In other words, `printstring` should not be constrained to an absolute location.

**Comment by hunter40415** [comment]
thanks for your explanation. I still a amateur at coding so I haven't
thought about that. Anyway thanks to your work I have done many cool thing
on my pico pi.
(Mind my bad English vocabulary).

**Comment by peterhinch** [comment]
You can always write your own function:
```python
def print_at(wri, text, row, col):
    Writer.set_textpos(row, col)
    wri.printstring(text)
```
then you can write
```python
wri = Writer(display, roman20)
print_at(wri, "Hello world", 0, 5)
```
I notice you use `x` and `y`. Graphics systems usually use `row`, `col`. The mathematical `x` coordinate is `col`, `y` is `row`. Just to confuse us :)
