### ISSUE TITLE
5x7 hand made fonts that work with writer.py

### ISSUE THREAD

**Issue by bradcar** [peterhinch/micropython-font-to-py#64]
Hi Peter, Really like your font_to_py.py and our writer. You mentioned _"For small fonts it is best to use hand-designed bitmapped font files. "_ I want to use font's generated by your code as well as a 5x7 for numbers letters. where would I find a font_5x7.py that is compatible with yours?   Been looking but can't find anything yet.

**Comment by bradcar** [comment]
Finally found one at: https://github.com/easytarget/microPyEZfonts/blob/main/examples/fonts/ezFBfont_07_font_tiny5_ascii.py

Might want to put reference to ez's fonts in your small font section of the readme, as others also may want to use both your work on writer, font_to_py, and larger fonts.  As well as smaller one.  THANKS AGAIN!

**Comment by peterhinch** [comment]
Thanks for the pointer. README.md now [updated](https://github.com/peterhinch/micropython-font-to-py/blob/master/README.md#31-small-fonts).
