### ISSUE TITLE
How to make font thai ?

### ISSUE THREAD

**Issue by Witawat** [peterhinch/micropython-font-to-py#65]
Hello

i try use -k thai and -k thailand not work
[THSarabunNew.zip](https://github.com/user-attachments/files/17533592/THSarabunNew.zip)

this font thai

abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!"#$%&'()*+,-./ก ข ฃ ค ฅ ฆ ง จ ฉ ช ซ ฌ ญ ฎ ฏ ฐ ฑ ฒ ณ ด ต ถ ท ธ น บ ป ผ ฝ พ ฟ ภ ม ย ร ฤ ล ฦ ว ศ ษ ส ห ฬ อ ฮ ฯ ะ ั า ำ ิ ี ึ ื ุ ู ฺ ฻ ฼ ฽ ฾ ฿ เ แ โ ใ ไ ๅ ๆ ็ ่ ้ ๊ ๋ ์ ํ ๎ ๏ ๐ ๑ ๒ ๓ ๔ ๕ ๖ ๗ ๘ ๙ ๚ ๛

**Comment by peterhinch** [comment]
Please see my response to your other issue.
